/* tslint:disable */
/* eslint-disable */
/**
 * JobCounselor API
 * Minimal API surface for the JobCounselor backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ProfilesIdPutRequest
 */
export interface ApiV1ProfilesIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ProfilesIdPutRequest
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ProfilesIdPutRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ProfilesIdPutRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ProfilesIdPutRequest
     */
    summary?: string;
}

/**
 * Check if a given object implements the ApiV1ProfilesIdPutRequest interface.
 */
export function instanceOfApiV1ProfilesIdPutRequest(value: object): value is ApiV1ProfilesIdPutRequest {
    return true;
}

export function ApiV1ProfilesIdPutRequestFromJSON(json: any): ApiV1ProfilesIdPutRequest {
    return ApiV1ProfilesIdPutRequestFromJSONTyped(json, false);
}

export function ApiV1ProfilesIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ProfilesIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function ApiV1ProfilesIdPutRequestToJSON(json: any): ApiV1ProfilesIdPutRequest {
    return ApiV1ProfilesIdPutRequestToJSONTyped(json, false);
}

export function ApiV1ProfilesIdPutRequestToJSONTyped(value?: ApiV1ProfilesIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fullName': value['fullName'],
        'email': value['email'],
        'phone': value['phone'],
        'summary': value['summary'],
    };
}

