/* tslint:disable */
/* eslint-disable */
/**
 * JobCounselor API
 * Minimal API surface for the JobCounselor backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EducationItem
 */
export interface EducationItem {
    /**
     * 
     * @type {string}
     * @memberof EducationItem
     */
    degree?: string;
    /**
     * 
     * @type {string}
     * @memberof EducationItem
     */
    institution?: string;
    /**
     * 
     * @type {Date}
     * @memberof EducationItem
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EducationItem
     */
    endDate?: Date | null;
}

/**
 * Check if a given object implements the EducationItem interface.
 */
export function instanceOfEducationItem(value: object): value is EducationItem {
    return true;
}

export function EducationItemFromJSON(json: any): EducationItem {
    return EducationItemFromJSONTyped(json, false);
}

export function EducationItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EducationItem {
    if (json == null) {
        return json;
    }
    return {
        
        'degree': json['degree'] == null ? undefined : json['degree'],
        'institution': json['institution'] == null ? undefined : json['institution'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
    };
}

export function EducationItemToJSON(json: any): EducationItem {
    return EducationItemToJSONTyped(json, false);
}

export function EducationItemToJSONTyped(value?: EducationItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'degree': value['degree'],
        'institution': value['institution'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString().substring(0,10)),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString().substring(0,10)),
    };
}

