/* tslint:disable */
/* eslint-disable */
/**
 * JobCounselor API
 * Minimal API surface for the JobCounselor backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExperienceItem
 */
export interface ExperienceItem {
    /**
     * 
     * @type {string}
     * @memberof ExperienceItem
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ExperienceItem
     */
    company?: string;
    /**
     * 
     * @type {Date}
     * @memberof ExperienceItem
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ExperienceItem
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceItem
     */
    description?: string;
}

/**
 * Check if a given object implements the ExperienceItem interface.
 */
export function instanceOfExperienceItem(value: object): value is ExperienceItem {
    return true;
}

export function ExperienceItemFromJSON(json: any): ExperienceItem {
    return ExperienceItemFromJSONTyped(json, false);
}

export function ExperienceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperienceItem {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'company': json['company'] == null ? undefined : json['company'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ExperienceItemToJSON(json: any): ExperienceItem {
    return ExperienceItemToJSONTyped(json, false);
}

export function ExperienceItemToJSONTyped(value?: ExperienceItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'company': value['company'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString().substring(0,10)),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString().substring(0,10)),
        'description': value['description'],
    };
}

