name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web-ui/package-lock.json
      - name: Install Node dependencies
        working-directory: web-ui
        run: npm ci
      - name: Lint frontend
        working-directory: web-ui
        run: npm run lint
      - name: Test frontend
        working-directory: web-ui
        run: npm run test -- --run
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -warnaserror
      - name: Test
        run: dotnet test

